FROM node:18-alpine AS base

# Install dependencies only when needed
FROM base AS deps
# Check https://github.com/nodejs/docker-node/tree/b4117f9333da4138b03a546ec926ef50a31506c3#nodealpine to understand why libc6-compat might be needed.
RUN apk add --no-cache libc6-compat
WORKDIR /app

# Install dependencies based on the preferred package manager
COPY package.json yarn.lock* package-lock.json* pnpm-lock.yaml* ./
RUN \
  if [ -f yarn.lock ]; then yarn --frozen-lockfile; \
  elif [ -f package-lock.json ]; then npm ci; \
  elif [ -f pnpm-lock.yaml ]; then yarn global add pnpm && pnpm i --frozen-lockfile; \
  else echo "Lockfile not found." && exit 1; \
  fi

FROM base AS dev

WORKDIR /app
COPY --from=deps /app/node_modules ./node_modules
COPY . .

# Rebuild the source code only when needed
FROM base AS builder
WORKDIR /app
COPY --from=deps /app/node_modules ./node_modules
COPY . .

# Next.js collects completely anonymous telemetry data about general usage.
# Learn more here: https://nextjs.org/telemetry
# Uncomment the following line in case you want to disable telemetry during the build.
ENV NEXT_TELEMETRY_DISABLED 1

# Input your own keys here
ENV DATABASE_URL=
ENV NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=
ENV CLERK_SECRET_KEY=
ENV GEMINI_API_KEY=
ENV NEXT_PUBLIC_BASE_URL=
ENV MONGODB_URI=
ENV MONGODB_DB_NAME=seratus_db
ENV NEXT_PUBLIC_CLIENT=
ENV MIDTRANS_SECRET=
ENV NEXT_PUBLIC_API=https://app.sandbox.midtrans.com/snap/v1/transactions
ENV NEXT_PUBLIC_WEBSOCKET_URL=ws://localhost:8080

# Add this line to enable standalone output
ENV NEXT_STANDALONE=1

RUN yarn build

# If using npm comment out above and use below instead
# RUN npm run build

# Production image, copy all the files and run next
FROM base AS runner
WORKDIR /app

# Uncomment the following line in case you want to disable telemetry during runtime.
ENV NEXT_TELEMETRY_DISABLED 1

ENV PINECONE_API_KEY=227fa340-c46b-46a2-a505-064a28989c8e

RUN addgroup --system --gid 1001 nodejs
RUN adduser --system --uid 1001 nextjs

# You need to copy the entire .next directory
COPY --from=builder --chown=nextjs:nodejs /app/.next ./.next
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/package.json ./package.json

USER nextjs

EXPOSE 3000

CMD ["yarn", "start"]