services: 
  seratus:
    container_name: seratus
    build:
      context: .
      target: dev
    restart: always
    command: yarn dev
    env_file:
      - .env.local
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    ports:
      - 3001:3001
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
