# To run the docker compose file: docker compose -f "docker-compose.prod.yml" up -d --build
services: 
  seratus:
    container_name: seratus
    build: .
    restart: always #change if you don't want your container restarting
    env_file:
      - .env.production
    ports:
      - 3002:3002
    networks:
      - app-network

networks:
  app-network:
    driver: bridge